### PR TITLE
add geckodriver note on Firefox WebDriver docs

### PR DESCRIPTION
**Pull request by luzfcb**

### CODE REVIEW

**Comment by andrewsmedina** [comment]
@luzfcb thank you!

**Comment by luzfcb** [comment]
@andrewsmedina :pray: if not asking too much, could you mark this pull-request with the label "Hacktoberfest"

**Comment by andrewsmedina** [comment]
@luzfcb I believe that this mark is unnecessary to be a hacktoberfest contribution.

**Comment by andrewsmedina** [comment]
@luzfcb you can check here: https://hacktoberfestchecker.herokuapp.com/?username=luzfcb

**Comment by luzfcb** [comment]
@andrewsmedina uhmm... cool.

**Pull request merged**
