### PR TITLE
Element screenshot

### LINKED ISSUE #500: support screenshot of element
solution: http://stackoverflow.com/a/15870708

### PR DESCRIPTION
**Pull request by gentoo90**
This adds `screenshot` method to `WebDriverElement` class. Depends on [`pillow`](https://pypi.python.org/pypi/Pillow/3.3.0).
Fixes #500 and supersedes #384.
I also updated `phantomjs` to `2.1.1` on travis since old version hangs.

### CODE REVIEW

**Comment by gentoo90** [comment]
BTW, is there any way to run only one single test from the test suite?

**Comment by avelino** [comment]
Not passed all the tests, some things are failing

**Comment by gentoo90** [comment]
I tweaked travis config a little, to fix chrome tests, but some tests in the suite still fail:
* Firefox - test_simple_type
* Phantomjs - cokies-related tests
* Python 3 - some type related failures

None of this is caused by my commits.
Tests actually fail on every pullrequest in queue.

**Comment by abathur** [comment]
@andrewsmedina This (at least by title) also seems to be eclipsed by #617

**Comment by andrewsmedina** [comment]
@abathur  you are right. I will close this.

**Pull request closed without merging**
