### PR TITLE
Make `fill_form` more robust by requiring form ID.

### PR DESCRIPTION
**Pull request by omaciel**
Current implementation for `fill_form` attempts to find fields by their names.
However, if the same name is found in multiple places, this method will either
fail with a `InvalidElementStateException` exception or the wrong field may be
filled.

Please see #564 for more info.

### CODE REVIEW

**Comment by omaciel** [comment]
@andrewsmedina mind taking a look at this? If it makes sense, I can update tests.

**Comment by omaciel** [comment]
Hmm perhaps I should make `form_id` optional? Also, add an optional `name` argument, so that people can still use the original functionality, but if a `name` or `id` are passed, then look for a form with it?

**Comment by omaciel** [comment]
Another possible solution:

```diff
diff --git a/splinter/driver/webdriver/__init__.py b/splinter/driver/webdriver/__init__.py
index cad1eba..d1cc559 100644
--- a/splinter/driver/webdriver/__init__.py
+++ b/splinter/driver/webdriver/__init__.py
@@ -417,12 +417,20 @@ class BaseWebDriver(DriverAPI):

     attach_file = fill

-    def fill_form(self, form_id, field_values):
-        form = self.find_by_xpath(
-            '//form[contains(@id, "{0}")]'.format(form_id))
+    def fill_form(self, field_values, form_id=None, name=None):
+        form = None
+
+        if name is not None:
+            form = self.find_by_name(name)
+        if form_id is not None:
+            form = self.find_by_xpath(
+                '//form[contains(@id, "{0}")]'.format(form_id))

         for name, value in field_values.items():
-            elements = form.find_by_name(name)
+            if form:
+                elements = form.find_by_name(name)
+            else:
+                elements = self.find_by_name(name)
             element = elements.first
             if (
                     element['type'] in ['text', 'password', 'tel'] or
```

**Comment by andrewsmedina** [comment]
@omaciel nice catch. Can you add a test to cover #564?

**Comment by omaciel** [comment]
@andrewsmedina will try though time is kinda tight this week :/ Could I also ask you to add a `hacktoberfest` label to #564 ? :)

**Comment by andrewsmedina** [comment]
@omaciel I will add the label. But all PR's open in October are valid for hacktober fest. If you want, you can close this PR and open another PR.

**Comment by omaciel** [comment]
@andrewsmedina tests are passing/failing and I'm not sure that I can look into all the different permutations... can you gimme a hand?

**Comment by andrewsmedina** [comment]
@omaciel all `fill_form` tests are here: https://github.com/cobrateam/splinter/blob/d3719283e29c4aae31dbaefacac29fbe2d5a331d/tests/form_elements.py

my suggestion is run in your machine against only one driver. I believe that `flaskdriver` is a good option. You can use this command to do it:

```
./run_tests.py -w tests/test_flaskclient.py
```

**Comment by omaciel** [comment]
@andrewsmedina I had to ask for help on this since getting lxml installed on a virtualenv on a MAC is a pain!!! Anyhow, it looks like your tests have been failing for a while so I don't expect that we will see a green build...

**Comment by andrewsmedina** [comment]
The tests are unstable on `travis` :(

But the `flask driver` tests are stable. And still `ok` with your PR. So, LGTM

**Comment by omaciel** [comment]
@andrewsmedina it fails to build lxml for me but someone ran the test you suggested (on Linux) and all tests passed.

```shell
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /Users/omaciel/.virtualenvs/splinter/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-t4Irzs/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2UPB0tpip-wheel- --python-tag cp27:
  Building lxml version 3.6.4.
  Building without Cython.
  Using build configuration of libxslt 1.1.29
  Building against libxml2/libxslt in the following directory: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.12-intel-2.7
  creating build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/builder.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/sax.py -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.macosx-10.12-intel-2.7/lxml
  creating build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  creating build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
  creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.12-intel-2.7/lxml
  copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.12-intel-2.7/lxml/includes
  creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources
  creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/rng
  creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.macosx-10.12-intel-2.7
  creating build/temp.macosx-10.12-intel-2.7/src
  creating build/temp.macosx-10.12-intel-2.7/src/lxml
  cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -Isrc/lxml/includes -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.12-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace
  cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.12-intel-2.7/src/lxml/lxml.etree.o -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.12-intel-2.7/lxml/etree.so
  ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'cc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml
  Running setup.py install for lxml ... error
    Complete output from command /Users/omaciel/.virtualenvs/splinter/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-t4Irzs/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cRdv21-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/omaciel/.virtualenvs/splinter/include/site/python2.7/lxml:
    Building lxml version 3.6.4.
    Building without Cython.
    Using build configuration of libxslt 1.1.29
    Building against libxml2/libxslt in the following directory: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    creating build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/builder.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/sax.py -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.macosx-10.12-intel-2.7/lxml
    creating build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    creating build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.12-intel-2.7/lxml/html
    creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron
    copying src/lxml/lxml.etree.h -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.12-intel-2.7/lxml
    copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.12-intel-2.7/lxml/includes
    creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources
    creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/rng
    creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.12-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.macosx-10.12-intel-2.7
    creating build/temp.macosx-10.12-intel-2.7/src
    creating build/temp.macosx-10.12-intel-2.7/src/lxml
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -Isrc/lxml/includes -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.12-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.12-intel-2.7/src/lxml/lxml.etree.o -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxslt -lexslt -lxml2 -lz -lm -o build/lib.macosx-10.12-intel-2.7/lxml/etree.so
    ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/Users/omaciel/.virtualenvs/splinter/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-t4Irzs/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cRdv21-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/omaciel/.virtualenvs/splinter/include/site/python2.7/lxml" failed with error code 1 in /private/tmp/pip-build-t4Irzs/lxml/
```

**Comment by omaciel** [comment]
@andrewsmedina 

```shell
$ ./run_tests.py -w tests/test_flaskclient.py      
.................................................................................................................................................................
----------------------------------------------------------------------
Ran 161 tests in 1.611s

OK
```

**Comment by andrewsmedina** [comment]
@omaciel thanks

**Comment by omaciel** [comment]
@andrewsmedina thank you too! When should I expect a new version in pypi?

**Pull request merged**
