### PR TITLE
Headless Firefox is possible

### PR DESCRIPTION
**Pull request by mpasternak**

### CODE REVIEW

**Comment by jsfehler** [comment]
@mpasternak You left an unused import in:
```from selenium.webdriver.firefox.firefox_binary import FirefoxBinary```

**Comment by mpasternak** [comment]
@jsfehler Corrected, thanks!

**Comment by andrewsmedina** [comment]
@mpasternak thanks for contribute

**Comment by mpasternak** [comment]
No way @andrewsmedina , thank YOU for maintaining a very helpful package!

**Pull request merged**
