### PR TITLE
Added support for User-Agent, SERVER_NAME and custom headers to djangocl...

### PR DESCRIPTION
**Pull request by dryobates**
Support for User-Agent and custom headers for djangoclient.

### CODE REVIEW

**Comment by andrewsmedina** [comment]
hi @dryobates can you add a test for this PR?

**Comment by dryobates** [comment]
Sure :)

**Comment by andrewsmedina** [comment]
@dryobates thank you!

**Comment by dryobates** [comment]
I've forgot to write that I've added missing tests. And some compatibility fixes for Python 3 for django, flask and firefox :)

**Comment by andrewsmedina** [comment]
@dryobates thank you!

**Pull request merged**
