### PR TITLE
Django 2

### PR DESCRIPTION
**Pull request by theunraveler**
After some pretty basic testing, it looks to me like splinter supports Django 2 without any modification, so I just removed the upper constraint.

Related to https://github.com/cobrateam/splinter/issues/605.

### CODE REVIEW

**Comment by theunraveler** [comment]
Test failures seem unrelated...

**Comment by andrewsmedina** [comment]
I believe that just make possible to install django 2 is not enough. It is necessary to update django in test-requirements and https://github.com/cobrateam/splinter/blob/master/test-requirements.txt and add a env in travis to test it: https://github.com/cobrateam/splinter/blob/master/.travis.yml#L28

**Comment by theunraveler** [comment]
OK, updated the requirements and build matrix. It looks like all of the relevant tests are passing (particularly `DJANGO_VERISON=2.0.6` with `PYTHON=3.4`). Since Django 2 does not support Python 2, I excluded that from the matrix.

There are quite a few other failing tests, but they appear to be unrelated to the changes in this PR.

**Comment by theunraveler** [comment]
Anything else I can do to push this PR forward? Thanks!

**Comment by theunraveler** [comment]
Nevermind, looks like it might have been picked up in https://github.com/cobrateam/splinter/commit/907208296d1936b2e8abfe21b7109cb0dad9e6a2#diff-2eeaed663bd0d25b7e608891384b7298. Thanks!

**Pull request closed without merging**
