### PR TITLE
android driver

### PR DESCRIPTION
**Pull request by sureshvv**
Selenium 2.45 supports this

### CODE REVIEW

**Comment by lrowe** [comment]
Why doesn't the existing remote webdriver client work here?

**Comment by sureshvv** [comment]
It works. Mostly. But still, there are a few reasons for this:

1.Recent selenium version has a webdriver called android. We can map splinter directly to that driver.

2. Certain operations are not supported by AndroidDriver (such as setWindowSize). We can handle those better.

Thank you for looking into this. Will be happy to make this mergeable.

**Comment by andrewsmedina** [comment]
@sureshvv sorry for the delay. Can you add tests?

**Comment by andrewsmedina** [comment]
I'm closing PR's longer than 2 years. So if someone else want to continue this works is just to reopen this PR or send another PR.

**Pull request closed without merging**
