### PR TITLE
initial suggestion for select_by_text instead of using value

### LINKED ISSUE #528: fill_form for selects should use option text and not value
Values of options should not be known by users of a browser, but the options text should be.

https://github.com/cobrateam/splinter/blob/1c08cbe59830d8004a5bf397391c586c78b9fa74/splinter/driver/webdriver/__init__.py#L435

### PR DESCRIPTION
**Pull request by peterlauri**
Closed #528

### CODE REVIEW

**Comment by andrewsmedina** [comment]
@peterlauri thank you

**Comment by peterlauri** [comment]
But I didn't write any tests yet :)

**Comment by andrewsmedina** [comment]
@peterlauri this code is already covered by `fill_form` tests :)

**Comment by peterlauri** [comment]
Sweet :)

**Pull request merged**
