### PR TITLE
browser stack driver implemented.

### PR DESCRIPTION
**Pull request by mroohian**
In order for **test_webdriver_browserstack.py** to pass _Browserstack_ credentials must be provided.

### CODE REVIEW

**Comment by lrowe** [comment]
Why is a specific browserstack driver needed? Credentials can be passed as keyword args when instantiating the remote Webdriver class: https://github.com/cobrateam/splinter/blob/0.7.2/splinter/driver/webdriver/remote.py

**Comment by neilsh** [comment]
I'm not the original submitter (and I realize this is 2 years after the PR was first created), but I think one reason is that browserstack's Selenium DesiredCapabilities takes keys with periods in them. [For example](https://www.browserstack.com/automate/capabilities): `browserstack.video`, `browserstack.timezone`, and `browserstack.debug`, and `browserstack.ie.noFlash`. 

Since each key in DesiredCapabilities is derived from the name of an argument passed to the `WebDriver()` constructor, I'm not sure there's any way to pass these keys using the remote WebDriver as it currently stands. As an abbreviated example, the following isn't valid python:

```python
Browser(driver_name='remote', browserstack.debug=True, browserstack.video=True)
```

**Comment by lrowe** [comment]
@nelish It's possible to pass arbitrary strings using keyword argument unpacking:
```python
Browser(driver_name='remote', **{"browserstack.debug": True, "browserstack.video": True})
```

**Comment by neilsh** [comment]
Excellent point about the argument unpacking. In that case, yeah, I can't think of any reason one would need specific browserstack support. ;)

**Comment by neilsh** [comment]
Also, I can confirm that the argument-unpacking solution you outlined works perfectly with browserstack. Here's an example that's worked well for me:

```python
wd_server = 'http://hub-cloud.browserstack.com/wd/hub'
browser = Browser(
                driver_name='remote',
                platform='windows',
                url=wd_server,
                browserName='chrome',
                name='TEST NAME',
                project='PROJECT NAME',  # used for grouping in browserstack UI
                resolution='1024x768',
                **{
                    'browserstack.debug': True,  # whether to take screenshots at each step
                    'browserstack.video': True,  # whether to record video of session
                    'browserstack.user': browserstack_user,
                    'browserstack.key': browserstack_key,
                }
            )
```

**Comment by andrewsmedina** [comment]
I'm -1 for a specific driver for browserstack

**Comment by neilsh** [comment]
Same here, although it might be worthwhile to include an example for browserstack (and other popular cloud services) in the documentation, similar to the example I posted above.

**Comment by andrewsmedina** [comment]
@neilsh I agree with you. Can you send a PR adding your example in the documentation?

**Comment by andrewsmedina** [comment]
I'm closing PR's longer than 2 years. So if someone else want to continue this works is just to reopen this PR or send another PR.

**Pull request closed without merging**
