### PR TITLE
removing external link bar in README

### PR DESCRIPTION
**Pull request by eltonjncorreia**
Excuse! Still wrong! I removed the bar

### CODE REVIEW

**Comment by eltonjncorreia** [comment]
I made a new pull request

**Comment by eltonjncorreia** [comment]
@andrewsmedina

**Comment by andrewsmedina** [comment]
@eltonjncorreia can I close this PR?

**Comment by eltonjncorreia** [comment]
sorry the links are wrong, I'm going to redo

**Pull request closed without merging**
